import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/COMPONENTS/LAYOUT/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Amazon Replica',
  description: 'Generated by syed salar alam ',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      <main>
      {children}
      </main>
      </body>
    </html>
  )
}
